
server:
  port: 8882
spring:
  application:
    name: nacos-consumer
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
logging:
  level:
    com.itbin.study.nacosconsume: debug
    org.apache.http.wire: debug
    org.apache.http.headers: debug
    okhttp3: debug
feign:
  client:
    config:
      nacos-provider:
        loggerLevel: FULL
  httpclient:
    enabled: false
    # 最大连接数
    max-connections: 200
    # 单个路由的最大连接数
    max-connections-per-route: 50
  okhttp:
    enabled: true


