
server:
  port: 8882
spring:
  application:
    name: sleuth-consumer
  sleuth:
    baggage-keys:
      - BaggraceId
feign:
  httpclient:
    enabled: false
    # 最大连接数
    max-connections: 200
    # 单个路由的最大连接数
    max-connections-per-route: 50
  okhttp:
    enabled: true
